# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://zjh.asia/life"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog-local'

# Basic metadata configuration for your blog.
title = "生活记录"
author = "Jinghe Zhang"
copyright = "Copyright © 2020, Jinghe Zhang."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/hello/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Blog of Jinghe Zhang"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["favicon.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "好"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  # hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  # dateFormat = "2006-01-02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true